version: "3.9"
services:
  book-catalog-db:
    # Название image, который нужно поднять
    image: postgres:14.4
    # Имя контейнера, то же что и --name
    container_name: book-catalog-db
    environment:
      POSTGRES_DB: book-catalog-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: parol
    ports:
      - "5433:5432"





